version: "3.7"  # optional since v1.27.0

services:
    beiw:
        container_name: be
        build: .
        volumes: 
            - ".:/app/"
            - "/app/node_modules"
        working_dir: "/app"
        ports:
            - 3000:3000