export const SET_PERMISSION = "SET_PERMISSION"

export const MODAL_ACTIVE = "MODAL_ACTIVE"

export const NOTIFICATION = "NOTIFICATION"

export const USER_SET_DATA = "USER_SET_DATA"
export const USER_SET_PERMISSION = "USER_SET_PERMISSION"


export const PROGRAM_SET_WASHING_MACHINE = "PROGRAM_SET_WASHING_MACHINE"
export const PROGRAM_SET_CLOTHES_DRYER = "PROGRAM_SET_CLOTHES_DRYER"
export const PROGRAM_GET_WASHING_MACHINE = "PROGRAM_GET_WASHING_MACHINE"
export const PROGRAM_GET_CLOTHES_DRYER = "PROGRAM_GET_CLOTHES_DRYER"
export const PROGRAM_STATUS = "PROGRAM_STATUS"
export const PROGRAM_UPDATE_WASHING_MACHINE_SUCCESS = "PROGRAM_GET_WASHING_MACHINE_SUCCESS"
export const PROGRAM_UPDATE_WASHING_MACHINE_PENDING = "PROGRAM_GET_WASHING_MACHINE_PENDING"
export const PROGRAM_UPDATE_WASHING_MACHINE_ERROR = "PROGRAM_GET_WASHING_MACHINE_ERROR"
export const PROGRAM_UPDATE_CLOTHES_DRYER_SUCCESS = "PROGRAM_UPDATE_CLOTHES_DRYER_SUCCESS"
export const PROGRAM_UPDATE_CLOTHES_DRYER_PENDING = "PROGRAM_UPDATE_CLOTHES_DRYER_PENDING"
export const PROGRAM_UPDATE_CLOTHES_DRYER_ERROR = "PROGRAM_UPDATE_CLOTHES_DRYER_ERROR"

export const BRANCH_GET = "BRANCH_GET"

export const WASHING_MACHINE_GET_ALL = "WASHING_MACHINE_GET_ALL"


export const ADMIN_SET_DATA = "ADMIN_SET_DATA"
export const CUSTOMER_SET_DATA = "CUSTOMER_SET_DATA"

export const PROMOTION_GET_SUCCESS = "PROMOTION_GET_SUCCESS"
export const PROMOTION_GET_PENDING = "PROMOTION_GET_PENDING"
export const PROMOTION_GET_ERROR = "PROMOTION_GET_ERROR"

export const WALLET_SET_DATA = "WALLET_SET_DATA"

export const POINT_REDEMTION_SET_DATA = "POINT_REDEMTION_SET_DATA"

export const DASHBOARD_ITEM_1_SET_DATA = "DASHBOARD_ITEM_1_SET_DATA"
export const DASHBOARD_ITEM_2_SET_DATA = "DASHBOARD_ITEM_2_SET_DATA"
export const DASHBOARD_ITEM_3_SET_DATA = "DASHBOARD_ITEM_3_SET_DATA"
export const DASHBOARD_ITEM_4_SET_DATA = "DASHBOARD_ITEM_4_SET_DATA"
export const DASHBOARD_ITEM_5_SET_DATA = "DASHBOARD_ITEM_5_SET_DATA"

export const CHAT_GET = "CHAT_GET"
export const CHAT_UPDATE = "CHAT_UPDATE"
export const CHAT_GET_DATA = "CHAT_GET_DATA"

export const SETPOINT_SET_DATA = "SETPOINT_SET_DATA"

export const REPORT_SALES_REPORT_SET_DATA = "REPORT_SALES_REPORT_SET_DATA"
export const REPORT_SALES_REPORT_PENDING_DATA = "REPORT_SALES_REPORT_PENDING_DATA"

export const REPORT_SALES_MONTH_REPORT_SET_DATA = "REPORT_SALES_MONTH_REPORT_SET_DATA"
export const REPORT_WASHING_REPORT_SET_DATA = "REPORT_WASHING_REPORT_SET_DATA"
export const REPORT_SALES_MONTH_REPORT_PENDING_DATA = "REPORT_SALES_MONTH_REPORT_PENDING_DATA"

export const ALERT_SHOW = "ALERT_SHOW"

export const SET_LANGUAGE = "SET_LANGUAGE"
export const SET_LANGUAGE_LIST = "SET_LANGUAGE_LIST"